/*
 * STEPPER_prg.c
 *
 *  Created on: Jul 22, 2025
 *      Author: acer
 */

#include <util/delay.h>
#include "../../LIB/STD_TYPES.h"
#include "../../LIB/BIT_MATH.h"
#include "../../MCAL/DIO/DIO_int.h"
#include "STEPPER_int.h"

void STEPPER_vInit(void) {
	MDIO_vSetPinDir(DIO_PORTC, STEPPER_BLUE_T, DIO_OUTPUT);
	MDIO_vSetPinDir(DIO_PORTC, STEPPER_PINK_T, DIO_OUTPUT);
	MDIO_vSetPinDir(DIO_PORTC, STEPPER_YELLOW_T, DIO_OUTPUT);
	MDIO_vSetPinDir(DIO_PORTC, STEPPER_ORANGE_T, DIO_OUTPUT);
}

void STEPPER_vRotateCW(f64 A_f64Speed) {
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_BLUE_T, DIO_HIGH);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_PINK_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_YELLOW_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_ORANGE_T, DIO_LOW);
	_delay_ms(A_f64Speed);

	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_BLUE_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_PINK_T, DIO_HIGH);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_YELLOW_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_ORANGE_T, DIO_LOW);
	_delay_ms(A_f64Speed);

	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_BLUE_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_PINK_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_YELLOW_T, DIO_HIGH);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_ORANGE_T, DIO_LOW);
	_delay_ms(A_f64Speed);

	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_BLUE_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_PINK_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_YELLOW_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_ORANGE_T, DIO_HIGH);
	_delay_ms(A_f64Speed);
}

void STEPPER_vRotateCCW(f64 A_f64Speed) {
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_BLUE_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_PINK_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_YELLOW_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_ORANGE_T, DIO_HIGH);
	_delay_ms(A_f64Speed);

	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_BLUE_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_PINK_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_YELLOW_T, DIO_HIGH);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_ORANGE_T, DIO_LOW);
	_delay_ms(A_f64Speed);

	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_BLUE_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_PINK_T, DIO_HIGH);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_YELLOW_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_ORANGE_T, DIO_LOW);
	_delay_ms(A_f64Speed);

	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_BLUE_T, DIO_HIGH);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_PINK_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_YELLOW_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_ORANGE_T, DIO_LOW);
	_delay_ms(A_f64Speed);
}

void STEPPER_vStop() {
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_BLUE_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_PINK_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_YELLOW_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPER_PORT, STEPPER_ORANGE_T, DIO_LOW);
}
